### ISSUE TITLE
undefined method `size' for nil:NilClass (NoMethodError) when installing

### ISSUE THREAD

**Issue by lenage** [ruby-concurrency/thread_safe#16]
I tried to install thread_safe version 0.3.5, but i got below error:

```
ERROR:  Error installing thread_safe:
	invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /home/vagrant/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/cache/thread_safe-0.3.5.gem
```

ruby version:

ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

gem version:
2.4.5

**Comment by pitr-ch** [comment]
Hi, I've just tried install the gem on the same versions (but os x) and all seems to work. Could you try to delete the cached `.gem` file and reinstall again to eliminate possibility of corrupted files?

**Comment by lenage** [comment]
@pitr-ch Hi, Thanks for checking, I deleted cached .gem and tried again,  still got above error. but it works if i downgrade to `0.3.4`

**Comment by pitr-ch** [comment]
@lenage could you post here a backtrace of the error? `gem install --backtrace` could help.

**Comment by lenage** [comment]
@pitr-ch 

```
vagrant@vagrant-ubuntu-trusty-64:~$ gem install thread_safe -v "0.3.5" --backtrace 
ERROR:  Error installing thread_safe:
	invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /home/vagrant/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/cache/thread_safe-0.3.5.gem
```

Here are some informations:
```
$ uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"

$ env
XDG_SESSION_ID=5
TERM=xterm-256color
SHELL=/bin/bash
SSH_CLIENT=10.0.2.2 54044 22
SSH_TTY=/dev/pts/0
USER=vagrant
SSH_AUTH_SOCK=/tmp/ssh-ae4n9pMdHB/agent.20161
MAIL=/var/mail/vagrant
PATH=/home/vagrant/.rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PWD=/home/vagrant
LANG=en_US.UTF-8
SHLVL=1
HOME=/home/vagrant
LOGNAME=vagrant
SSH_CONNECTION=10.0.2.2 54044 10.0.2.15 22
LC_CTYPE=en_US.UTF-8
XDG_RUNTIME_DIR=/run/user/1000
_=/usr/bin/env
vagrant@vagran
```

**Comment by jdantonio** [comment]
@lenage Thank you for the detailed info! This is the first problem that's been reported so we'll look into this ASAP. I see that you are using Vagrant. :+1: I use Vagrant extensively at work and to build the concurrent-ruby gem. I'll setup a VM like yours to troubleshoot the error you are experiencing.

**Comment by jdantonio** [comment]
@lenage Are you using RVM or another Ruby version manager?

**Comment by jdantonio** [comment]
@lenage Thus far I have been unable to reproduce the error. I've setup an Ubuntu VM using vagrant. The version of Linux I used is:

```
vagrant@vagrant-ubuntu-trusty-64:~/ruby-2.2.1$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```

I installed MRI `ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]` from source and was able to successfully install thread_safe using `sudo gem install thread_safe -v "0.3.5" --backtrace`. I also installed RVM `rvm 1.26.11 (latest)` and installed MRI `ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]` under RVM. I was able to successfully install thread_safe using `gem install thread_safe -v "0.3.5" --backtrace` under that as well.

Can you please download the `thread_safe-0.3.5.gem` gem package directly from the GitHub [release](https://github.com/ruby-concurrency/thread_safe/releases/tag/v0.3.5) page and try to install it? As @pitr-ch suggested, you may have a corrupt file in your gem cache.

**Comment by lenage** [comment]
@jdantonio Yes, i'm using `rbenv 0.4.0`.

Thanks for the help, I downloaded the gem file in release page and it installed successfully.

```
gem i thread_safe-0.3.5.gem 
Successfully installed thread_safe-0.3.5
Parsing documentation for thread_safe-0.3.5
Installing ri documentation for thread_safe-0.3.5
Done installing documentation for thread_safe after 0 seconds
1 gem installed
```

**Comment by jdantonio** [comment]
@lenage I just tried again with rbenv and was able to successfully install `thread_safe`, so I definitely think your cached gem package was corrupt. Let us know if you have any other problems.
