### ISSUE TITLE
About Ruby 1.8

### ISSUE THREAD

**Issue by dzjuck** [ruby-concurrency/thread_safe#19]
Should we remove code related to Ruby 1.8?

I tried to install dependencies for Ruby 1.8 and had fail because some of them need Ruby 1.9 at least.

**Comment by jdantonio** [comment]
Absolutely. We still support 1.9.3 ut nothing earlier.

**Comment by dzjuck** [comment]
Great! I will make pull request

**Comment by jdantonio** [comment]
Thank you!
