### ISSUE TITLE
Need a lock-free Cache for MRI

### ISSUE THREAD

**Issue by headius** [ruby-concurrency/thread_safe#3]
At RubyFuza 2015, @tenderlove talked about how Rails lazily compiles views, which currently requires locking and blocking. I suggested using ThreadSafe::Cache to him, since I know it doesn't need locks on JRuby and it can guarantee once-only value population. He crushed my hopes by pointing out that Cache on MRI *does* use locks.

So we need to fix that.

We do have atomic support through atomic gem (now in concurrent-ruby) so it should be possible to implement a lock-free Cache for MRI too. It would definitely increase its utility.

Filing here since we have not decided how the merge of thread_safe into concurrent-ruby will proceed (or when).

**Comment by tenderlove** [comment]
I think we currently get around this by using DCLs.  So I'm not sure if it's really a high priority. ¯\_(ツ)_/¯

**Comment by jdantonio** [comment]
I agree that this would increase the utility of the gem overall. Plus, we strive to provide consistent behavior across all Ruby platforms whenever possible. More lock-free backends means more consistency so I think we should look into it.

**Comment by pitr-ch** [comment]
@tenderlove what do you mean by DCL? I've tried googling but e.g. `Disney Cruise Line` is probably not what you meant :)

**Comment by tenderlove** [comment]
[DCL = "Double Checked Locking"](http://en.wikipedia.org/wiki/Double-checked_locking)

**Comment by pitr-ch** [comment]
Right thanks, https://github.com/ruby-concurrency/thread_safe/blob/master/lib/thread_safe/mri_cache_backend.rb#L18-L24

**Comment by thedarkone** [comment]
Wait a minute guys! Don't go on a Disney Cruise Line just yet!

Firstly, @tenderlove: I think Rails' lazily compiled views are reasonably well implemented, in fact given 100 threads the code should be able to concurrently look up 100 templates and then concurrently compile them. It is also already [heavily relying on `TS::Cache`](https://github.com/rails/rails/blob/dc7ed96adc4e0b4c8a2cc524bbfc7172c007ca74/actionview/lib/action_view/template/resolver.rb#L38-L48).

Secondly, @jdantonio and @pitr-ch: I maintain that `TS::Cache`'s MRI specific backend is well suited: it is reasonably (given MRI's GVL problems) concurrent, fast and memory efficient.

**Comment by jdantonio** [comment]
Since there has been no further conversation on this, I'm going to close the issue. Now that thread_safe has been merged into concurrent-ruby ([here](https://github.com/ruby-concurrency/concurrent-ruby/pull/386)), we can revisit this conversation over there if it becomes an issue.
