### ISSUE TITLE
thread_safe 0.3.5 warnings ruby 2.4

### ISSUE THREAD

**Issue by eproulx-petalmd** [ruby-concurrency/thread_safe#30]
Hi,

I know `thread_safe` is now part of `concurrent_ruby` but with rails 4 depending on it and having `4.2.8` ready for ruby `2.4`, there's still some warnings. Any plans for fixing them ?

Here's the thread in rails : https://github.com/rails/rails/issues/28099#issuecomment-281769865

Thanks

**Comment by jdantonio** [comment]
PR #29, merged last month, fixes those warnings. I believe @pitr-ch is planning a new release soon.

**Comment by thedarkone** [comment]
`0.3.6` is out, closing. Thx!
