### ISSUE TITLE
The "Homepage" link from RubyGems.org should point to https://github.com/ruby-concurrency/thread_safe

### ISSUE THREAD

**Issue by donv** [ruby-concurrency/thread_safe#5]
The "Homepage" link from RubyGems.org still points to https://github.com/headius/thread_safe .

It should point to https://github.com/ruby-concurrency/thread_safe .

**Comment by jdantonio** [comment]
@donv Good catch! I've updated what links I can but the others require a new gem to be uploaded. I'll make those updates when I release 0.3.5
